package voices

// full tables
// http://www.lingoes.net/en/translator/langcode.htm
// https://www.science.co.il/language/Codes.php
// https://cloud.google.com/text-to-speech/docs/voices

const (
	English    = "en" // English US
	EnglishUK  = "en-UK"
	EnglishAU  = "en-AU"
	Japanese   = "ja"
	German     = "de"
	Spanish    = "es"
	Russian    = "ru"
	Arabic     = "ar"
	bengali    = "bn"
	Czech      = "cs"
	Danish     = "da"
	Dutch      = "nl"
	Finnish    = "fi"
	Greek      = "el"
	Hindi      = "hi"
	Hungarian  = "hu"
	Indonesian = "id"
	Khmer      = "km"
	Latin      = "la"
	Italian    = "it"
	Norwegian  = "no" // nb
	Polish     = "pl"
	Slovak     = "sk"
	Swedish    = "sv"
	Thai       = "th"
	Turkish    = "tr"
	Ukrainian  = "uk"
	Vietnamese = "vi"
	Afrikaans  = "af"
	Bulgarian  = "bg"
	Catalan    = "ca"
	Welsh      = "cy"
	Estonian   = "et"
	French     = "fr"
	Gujarati   = "gu"
	Icelandic  = "is"
	Javanese   = "jv"
	Kannada    = "kn"
	Korean     = "ko"
	Latvian    = "lv"
	Malayalam  = "ml"
	Marathi    = "mr"
	Malay      = "ms"
	Nepali     = "ne"
	Portuguese = "pt"
	Romanian   = "ro"
	Sinhala    = "si"
	Serbian    = "sr"
	Sundanese  = "su"
	Tamil      = "ta"
	Telugu     = "te"
	Tagalog    = "tl"
	Urdu       = "ur"
	Chinese    = "zh"
	Swahili    = "sw"
	Albanian   = "sq"
	Burmese    = "my" //not with english
	Macedonian = "mk"
	Armenian   = "hy"
	Croatian   = "hr"
	Esperanto  = "eo"
	Bosnian    = "bs"
)
